name: .NET

on:
  push:
    branches: [ base ]
  pull_request:
    branches: [ base ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Fix .Net Standard Environment
      run: dotnet add package Microsoft.CSharp --version 4.7.0
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
